### ISSUE TITLE
Error with Registration Endpoint

### ISSUE THREAD

**Issue by ArabFullStack** [ArabFullStack/Sell-it-All-BE#6]
There was an issue when I tried using the same email to register. I would suggest you try  make sure the email  doesn't already exist. You can use: 
    const user = await User.findOne({ email });
    if (user)
      return res
        .status(401)
        .json({ message: "The email address you have entered is already associated with another account." });

Kindly find attached the errors.
![err](https://user-images.githubusercontent.com/81173859/137374887-972ac85a-e6d7-425a-ac5e-aca84610a554.PNG)
![err2](https://user-images.githubusercontent.com/81173859/137374888-c020fe77-99fc-42f5-a98a-a622e89bf903.PNG)

**Comment by Norman-86** [comment]
This was resolved
